create_store:
  name: Create Store
  description: Create a new store and its shopping list.
  fields:
    store_name:
      name: Store Name
      description: The name of the store to create.
      required: true
      example: "Costco"
      selector:
        text:

remove_store:
  name: Remove Store
  description: Removes a store from the sore list.
  fields:
    store_name:
      name: Store Name
      description: The name of the store to remove.
      required: true
      example: "Costco"
      selector:
        text:


add_item:
  name: Add item
  description: Adds an item to the selected store
  fields:
    store_name:
      name: Store Name
      description: The name of the store being shopped at.
      required: true
      example: "Costco"
      selector:
        text:
    item_name:
      name: Item Name
      description: The name of the item being added to the stores list
      required: true 
      selector: 
        text:
    quantity:
      name: quantity
      description: The amount of items being added. Default is 1.
      required: false
      selector:
        number:
          min: 1
          mode: box
    notes:
      name: notes
      description: Any notes about the given item
      required: false
      selector:
        text:
         
remove_item:
  name: Remove Item
  description: Removes and item from the list of the selected store
  fields:
    store_name:
      name: Store Name
      description: The name of the store being shopped at.
      required: true
      example: "Costco"
      selector:
        text:
    uid:
      name: ID Number
      description: system generated id number for that item place
      required: true
      selector:
        text:
    
clear_full_list:
  name: Clear full list
  description: Clears the entierty of a shopping list for the selected store
  fields:
    store_name:
      name: Store Name
      description: The name of the store being shopped at.
      required: true
      example: "Costco"
      selector:
        text:

clear_bought:
  name: Clear bought list
  description: Clears all items marked as bought from the selected list
  fields:
    store_name:
      name: Store Name
      description: The name of the store being shopped at.
      required: true
      example: "Costco"
      selector:
        text:

toggle_bought: 
  name: Toggle bought
  description: toggles if an item is marked as bought
  fields:
    store_name:
      name: Store Name
      description: The name of the store being shopped at.
      required: true
      example: "Costco"
      selector:
        text:
    uid:
      name: ID Number
      description: system generated id number for that item place
      required: true
      selector:
        text: